### ISSUE TITLE
Nord.xml causes NP++ to crash

### ISSUE THREAD

**Issue by Daeronicus** [arcticicestudio/nord-notepadplusplus#14]
Currently using Notepad++ v8.1.4 and when changing theme to nord np++ crashes with this message
![np with nordxml crash](https://user-images.githubusercontent.com/90194317/132216967-d8e77df1-f477-465c-8cb1-17a53bdbefa6.png)

**Comment by Daeronicus** [comment]
Nord.xml linked in the main page downloads in bad formated file if you right click and download file as. Open the link, copy and paste the content of nord.xml in a new text file and save as xml. Now will work. If you righ click the link and download the file it will look as the image.
![imagen](https://user-images.githubusercontent.com/90194317/132226567-1f65f8ba-583b-4efe-9fa8-6f55e3c27f60.png)

**Comment by arcticicestudio** [comment]
Hi @Daeronicus :wave:

Using the "save file as" function of your browser will always download the page the link points at which is just a simple HTML page. This is nothing special to this repository but a basic browser function that will work the same for every link.
A possible improvement for the repository documentation could be to change the target to the `raw.githubuercontent.com` domain (https://raw.githubusercontent.com/arcticicestudio/nord-notepadplusplus/develop/src/xml/nord.xml) which will serve the content with content type `text/plain`. This would result in a file with the correct format.
Anyway, this issue is resolved, but feel free to submit a PR for the proposed change if you like to improve this use case.
